<a href="https://colab.research.google.com/github/Stitaprajna/Machine-Leaning-Models/blob/main/K_Means_Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**K-Means Algorithm**
1. Randomly intialize the centres of each cluster.
2. Each data point is assigned a cluster based on the Euclidean distance, the cluster closest to it.
3. The positions of the centroids are updated, by recalculating the centers.
4. Until the centroids change significantly, we need to iterate 2 and 3 step.

In [82]:
import numpy as np
import random

data = [[random.randint(0,1000) for _ in range(10)] for _ in range(1000)]
data = np.array(data)

In [83]:
def k_means_clustering(data,number_of_clusters):
  cluster_positions = [[random.randint(0,1000) for _ in range(data.shape[1])] for _ in range(number_of_clusters)]
  cluster_positions = np.array(cluster_positions)
  points_in_cluster = [[] for i in range(number_of_clusters)]
  i = 0

  while i<500:
    for point in data:
      distances_from_centroids = np.array([(sum((point - cluster_positions[cluster])**2))**0.5 for cluster in range(len(cluster_positions))])
      cluster_id = np.argmin(distances_from_centroids)
      # print(cluster_id)
      np.append(points_in_cluster[cluster_id],point)
      points_in_cluster[cluster_id].append(point)
    cluster_positions_updated = [np.mean(np.array(points_in_cluster[cluster]),axis=0) if len(points_in_cluster[cluster])>0 else cluster_positions[cluster]  for cluster in range(len(points_in_cluster))]
    print((np.sum((cluster_positions - cluster_positions_updated)**2,axis=1))**0.5)
    cluster_positions = np.array(cluster_positions_updated)
    i+=1

In [ ]:
k_means_clustering(data,4)

[593.37683689 633.81429451 652.45613422 803.29628067]
[33.43835718 22.97937551 27.89395558 80.62695105]
[16.43770892 12.50272172 12.94471951 33.46299305]
[10.45007527  8.40439018  8.01653969 13.9185172 ]
[ 8.17410464  6.85251517  5.34159317 10.94555211]
[6.49868585 5.69063195 4.17182644 8.89758283]
[5.4446762  4.7958749  3.43312665 7.45591071]
[4.49506835 4.06157757 3.00924656 6.18686594]
[3.73039596 3.7142131  2.35745124 5.66954598]
[3.21192536 3.59656931 2.03754114 5.41662771]
[2.77152975 3.23716314 1.63986515 4.40559466]
[2.67755283 2.78615057 1.37014374 3.98224729]
[2.36147362 2.6432824  1.16191039 3.48698113]
[2.04697701 2.39113584 0.99779523 3.09670924]
[1.87906985 2.06865124 0.97268463 2.91766979]
[1.78921411 1.86488922 0.88000165 2.62198327]
[1.59242142 1.64402446 0.82322347 2.35723107]
[1.48518151 1.46020271 0.74846728 2.32349669]
[1.39275854 1.30557886 0.69897319 2.05279804]
[1.26124347 1.17428018 0.75647944 1.87351614]
[1.22486015 1.1168248  0.68543189 1.72271381]
[1.2001310